require("modules.monitors")
require("modules.autostart")
require("modules.env")
require("modules.decorations")
require("modules.misc")
require("modules.input")
require("modules.keybindings")
require("modules.windows")
